from enum import Enum
from typing import Annotated, Dict, List, Literal, Union
from fastapi import FastAPI
from pydantic import BaseModel, Extra, Field

app = FastAPI()

class BaseColumn(BaseModel):
    sequence: int = Field(title = 'Sequence number', description='The order of things, as defined [here](http://johngom.com)')

class FoodColumn(BaseColumn, extra=Extra.forbid):
    type: Literal["food"]

class RecipeColumn(BaseColumn, extra=Extra.forbid):
    type: Literal["recipe"]

class CustomColumn(BaseColumn, extra=Extra.allow):
    type: Literal["custom"]
    code: str


class FacetCode(Enum):
    acidity = 'acidity'
    added_salt = 'added-salt'
    added_sugars = 'added-sugars'
    alcohol = 'alcohol'
    alpha_linolenic_acid = 'alpha-linolenic-acid'
    ammonium_chloride = 'ammonium-chloride'
    arachidic_acid = 'arachidic-acid'
    arachidonic_acid = 'arachidonic-acid'
    bcaa = 'bcaa'
    behenic_acid = 'behenic-acid'
    beta_alanine = 'beta-alanine'
    beta_carotene = 'beta-carotene'
    beta_glucan = 'beta-glucan'
    bicarbonate = 'bicarbonate'
    biotin = 'biotin'
    butyric_acid = 'butyric-acid'
    caffeine = 'caffeine'
    calcium = 'calcium'
    calcium_iodate_anhydrous = 'calcium-iodate-anhydrous'
    capric_acid = 'capric-acid'
    caproic_acid = 'caproic-acid'
    caprylic_acid = 'caprylic-acid'
    carbohydrates = 'carbohydrates'
    carbohydrates_total = 'carbohydrates-total'
    carbon_footprint = 'carbon-footprint'
    carnitine = 'carnitine'
    casein = 'casein'
    cassia_gum = 'cassia-gum'
    cerotic_acid = 'cerotic-acid'
    chloride = 'chloride'
    chlorophyl = 'chlorophyl'
    cholesterol = 'cholesterol'
    choline = 'choline'
    choline_chloride = 'choline-chloride'
    chromium = 'chromium'
    copper = 'copper'
    copper_ii_sulphate_pentahydrate = 'copper-ii-sulphate-pentahydrate'
    creatine = 'creatine'
    dihomo_gamma_linolenic_acid = 'dihomo-gamma-linolenic-acid'
    docosahexaenoic_acid = 'docosahexaenoic-acid'
    dry_residue = 'dry-residue'
    eicosapentaenoic_acid = 'eicosapentaenoic-acid'
    elaidic_acid = 'elaidic-acid'
    energy = 'energy'
    energy_from_fat = 'energy-from-fat'
    energy_kcal = 'energy-kcal'
    energy_kj = 'energy-kj'
    erucic_acid = 'erucic-acid'
    erythritol = 'erythritol'
    fat = 'fat'
    fiber = 'fiber'
    fluoride = 'fluoride'
    folates = 'folates'
    fructose = 'fructose'
    galactose = 'galactose'
    gamma_linolenic_acid = 'gamma-linolenic-acid'
    gamma_oryzanol = 'gamma-oryzanol'
    glucose = 'glucose'
    glycemic_index = 'glycemic-index'
    gondoic_acid = 'gondoic-acid'
    hydrogencarbonate = 'hydrogencarbonate'
    inositol = 'inositol'
    insoluble_fiber = 'insoluble-fiber'
    iodine = 'iodine'
    iron = 'iron'
    iron_ii_sulphate_monohydrate = 'iron-ii-sulphate-monohydrate'
    isomalt = 'isomalt'
    l_arginine = 'l-arginine'
    l_citrulline = 'l-citrulline'
    l_cysteine = 'l-cysteine'
    l_glutamine = 'l-glutamine'
    l_glutathione = 'l-glutathione'
    l_isoleucine = 'l-isoleucine'
    l_leucine = 'l-leucine'
    l_valine = 'l-valine'
    lactose = 'lactose'
    lauric_acid = 'lauric-acid'
    lignoceric_acid = 'lignoceric-acid'
    linoleic_acid = 'linoleic-acid'
    magnesium = 'magnesium'
    maltitol = 'maltitol'
    maltodextrins = 'maltodextrins'
    maltose = 'maltose'
    manganese = 'manganese'
    manganous_sulphate_monohydrate = 'manganous-sulphate-monohydrate'
    mead_acid = 'mead-acid'
    melatonin = 'melatonin'
    melissic_acid = 'melissic-acid'
    methylsulfonylmethane = 'methylsulfonylmethane'
    molybdenum = 'molybdenum'
    monounsaturated_fat = 'monounsaturated-fat'
    montanic_acid = 'montanic-acid'
    myristic_acid = 'myristic-acid'
    nervonic_acid = 'nervonic-acid'
    nitrate = 'nitrate'
    nitrite = 'nitrite'
    nucleotides = 'nucleotides'
    oleic_acid = 'oleic-acid'
    oligosaccharide = 'oligosaccharide'
    omega_3_fat = 'omega-3-fat'
    omega_6_fat = 'omega-6-fat'
    omega_9_fat = 'omega-9-fat'
    palmitic_acid = 'palmitic-acid'
    pantothenic_acid = 'pantothenic-acid'
    ph = 'ph'
    phosphorus = 'phosphorus'
    phylloquinone = 'phylloquinone'
    polydextrose = 'polydextrose'
    polyols = 'polyols'
    polyunsaturated_fat = 'polyunsaturated-fat'
    potassium = 'potassium'
    potassium_iodide = 'potassium-iodide'
    protein_value = 'protein-value'
    proteins = 'proteins'
    psicose = 'psicose'
    salt = 'salt'
    saturated_fat = 'saturated-fat'
    selenium = 'selenium'
    serum_proteins = 'serum-proteins'
    silica = 'silica'
    sodium = 'sodium'
    sodium_selenite = 'sodium-selenite'
    soluble_fiber = 'soluble-fiber'
    sorbitol = 'sorbitol'
    spermidine = 'spermidine'
    starch = 'starch'
    stearic_acid = 'stearic-acid'
    sucrose = 'sucrose'
    sugars = 'sugars'
    sulphate = 'sulphate'
    taurine = 'taurine'
    trans_fat = 'trans-fat'
    unsaturated_fat = 'unsaturated-fat'
    vitamin_a = 'vitamin-a'
    vitamin_b1 = 'vitamin-b1'
    vitamin_b12 = 'vitamin-b12'
    vitamin_b2 = 'vitamin-b2'
    vitamin_b6 = 'vitamin-b6'
    vitamin_b9 = 'vitamin-b9'
    vitamin_c = 'vitamin-c'
    vitamin_d = 'vitamin-d'
    vitamin_e = 'vitamin-e'
    vitamin_k = 'vitamin-k'
    vitamin_pp = 'vitamin-pp'
    water = 'water'
    water_hardness = 'water-hardness'
    zinc = 'zinc'
    zinc_sulphate_monohydrate = 'zinc-sulphate-monohydrate'

class FoodMetadata(BaseModel):
    columns: Dict[str, Annotated[FoodColumn | RecipeColumn | CustomColumn, Field(discriminator='type')]]
    facets: Dict[FacetCode, float]

@app.put("/metadata")
def put_metadata(metadata: FoodMetadata):
    return
